# Build and deploy a EAP8 server with Multiple Deployments
:toc:               left

This example shows how to provision a plain EAP 8 server without any deployment.

### Build the container image that contains the server

To provision EAP 8 and create a container image with it, run the following commands:

[source,bash]
----
mvn clean package
----

## Run the container image

The container image `eap/eap8-server:latest` contains an EAP 8 without any deployments. You can still run it with:

[source,bash]
----
docker run -p 8080:8080 eap/eap8-server:latest
----

In the logs, we see that the server is up and running without any deployments

[source,bash]
----
8:51:01,997 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: JBoss EAP 8.0.0.Beta (WildFly Core 19.0.0.Beta16-redhat-00004) started in 658ms - Starte
----

If you have a web archive (WAR), you can then _mount_ it in the image so that the server will deploy it when the container image is run.
For example, if I have a `helloworld.war` on my local file system, I can deploy it in the container image with:

[source,bash]
----
docker run -p 8080:8080 -v $(pwd)/helloworld.war:/opt/server/standalone/deployments/ROOT.war  eap/eap8-server:latest
----

When the server boots, it now deploys the WAR (and put it at the root of the HTTP endpoint)

[source,bash]
----
08:54:26,844 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "ROOT.war" (runtime-name: "ROOT.war")
...
08:54:28,647 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 30) WFLYSRV0010: Deployed "ROOT.war" (runtime-name : "ROOT.war")
08:54:28,670 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: JBoss EAP 8.0.0.Beta (WildFly Core 19.0.0.Beta16-redhat-00004) started in 2321ms - Started 275 of 368 services (142 services are lazy, passive or on-demand) - Server configuration file in use: standalone.xml
----

The web application can now be accessed from the image:

[source,bash]
----
$ curl http://localhost:8080/HelloWorld
<html><head><title>helloworld</title></head><body>
<h1>Hello World!</h1>
</body></html>
----
