# Build and deploy a EAP8 application on OpenShift

This example shows how to build a EAP8 application on OpenShift using the zipped Maven repository.

Normally, there is no need to use this zipped Maven repository when EAP artifacts are all available for Red Hat MRRC.
But there are cases where the users wants to build EAP without internet access.

In order to do so, we will fetch the zipped Maven repository and put it in a scratch container image so we can pull the artifacts from there during the S2I build phase.

## Downlaoad EAP maven repository zip, add the application dependencies and put it in a container image

[source,bash]
----
$ cd ~/tmp
$ wget -c <url to jboss-eap-8.0.0.Beta maven-repository.zip> --no-check-certificate
$ unzip jboss-eap-8.0.0.Beta-redhat-xxxxxxxx-maven-repository.zip
$ cp -rf jboss-eap-8.0.0.Beta-maven-repository/maven-repository offline-maven-repo
----

To add all the application dependencies to this offline repo,
we build the app and use the `dependency:go-offline` goal

[source,bash]
----
$ export LOCAL_M2=~/tmp/offline-maven-repo
mvn -Dmaven.repo.local=$LOCAL_M2 clean package -Popenshift dependency:go-offline
----

Once that's done, all artifacts required to build the application and provision EAP are in the ~/tmp/offline-maven-repo directory.
Let's create a Docker image that contains this directory.

[source,bash]
----
$ cd ~/tmp
$ cat Dockerfile
FROM scratch
COPY offline-maven-repo /maven-repository
$ docker build -t offline-maven-repo .
----

## Push this image to OpenShift

[source,bash]
----
$ oc registry login
$ docker login -u openshift -p $(oc whoami -t) default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com
$ docker tag  offline-maven-repo default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com/jmesnil1-dev/offline-maven-repo
$ docker push default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com/jmesnil1-dev/offline-maven-repo
----

## Create a Helm release to build and deploy the application

[source,bash]
----
$ helm repo add wildfly http://docs.wildfly.org/wildfly-charts/
$ helm install eap-offline-example -f helm.yaml wildfly/wildfly
----

## Update the BuildConfig

The `BuildConfig` needs to be updated to inject the docker image containing the EAP artifacts during the S2I build phase.
Edit it with `oc edit buildconfig eap-offline-example-build-artifacts`:

Replace:

[source,yaml]
----
source:
    git:
      uri: https://github.com/jmesnil/eap-offline-example.git
    type: Git
----

by

[source,yaml]
----
source:
    git:
      uri: https://github.com/jmesnil/eap-offline-example.git
    images:
      - from:
          kind: ImageStreamTag
          name: 'offline-maven-repo:latest'
        paths:
          - sourcePath: /maven-repository
            destinationDir: ./offline-maven-repo
    type: Git
----

And add the following env vars to `strategy.sourceStrategy.env`:

[source,yaml]
----
        - name: MAVEN_LOCAL_REPO
          value: ./offline-maven-repo/maven-repository
        - name: MAVEN_ARGS_APPEND
          value: '-o'
----

Retrigger a build if needed.

At the end of the S2I build phase, the application image will contained the application provisioned with EAP8.

[source,bash]
----
$ oc logs deployment/eap-offline-example
...
14:22:54,324 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: JBoss EAP 8.0.0.Beta (WildFly Core 19.0.0.Final-redhat-20220523) started in 13706ms - St
...
----