# Build and deploy a EAP8 server with Multiple Deployments
:toc:               left

This example shows how to provision an EAP 8 server with multiple deployments.
It uses a Maven assembly to copy the deployments into the provisioned server

[source]
----
.
├── README.adoc
├── application1 # the 1st deployment
│   ├── pom.xml # a regular WAR deployment
│   └── src
├── application2 # the 2nd deployment
│   ├── pom.xml # a regular WAR deployment
│   └── src
├── local-eap-settings.xml
├── pom.xml # the Parent POM
└── server # the Maven module responsible for provisioning EAP 8 and copying the deployments
    └── pom.xml # Use the eap-maven-plugin to provision EAP 8
----

## Build and run on local machine

If you need to build and provision the application on your own machine with an internet access, there are few steps to do.

### Download EAP maven repository zip

[source,bash]
----
$ cd ~/tmp
$ wget -c <url to jboss-eap-8.0.0.Beta maven-repository.zip> --no-check-certificate
$ unzip jboss-eap-8.0.0.Beta-redhat-xxxxxxxx-maven-repository.zip
----

### Build the application

Update the path to the EAP 8 maven repository in the  `local-eap-settings.xml` file:

[source,bash]
----
$ vi local-eap-settings.xml
----

Build the application by using the EAP 8 Maven repo as a remote  Maven repository.

[source,bash]
----
$ mvn -s local-eap-settings.xml clean package
----

### Run the application


[source,bash]
----
$ ./server/target/server/bin/standalone.sh
...
09:53:49,712 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 30) WFLYSRV0010: Deployed "application2-1.0.0.Final.war" (runtime-name : "application2-1.0.0.Final.war")
09:53:49,712 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 30) WFLYSRV0010: Deployed "application1-1.0.0.Final.war" (runtime-name : "application1-1.0.0.Final.war")
...
09:53:49,747 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: JBoss EAP 8.0.0.Beta (WildFly Core 19.0.0.Final-redhat-20220627) started in 3930ms - Started 344 of 429 services (136 services are lazy, passive or on-demand) - Server configuration file in use: standalone.xml
----

## Build and deploy on OpenShift

This example shows how to build a EAP8 application on OpenShift using the zipped Maven repository.

Normally, there is no need to use this zipped Maven repository when EAP artifacts are all available for Red Hat MRRC.
But there are cases where the users wants to build EAP without internet access.

In order to do so, we will fetch the zipped Maven repository and put it in a scratch container image so we can pull the artifacts from there during the S2I build phase.

### Download EAP maven repository zip and put it in a container image

[source,bash]
----
$ cd ~/tmp
$ wget -c <url to jboss-eap-8.0.0.Beta maven-repository.zip> --no-check-certificate
$ unzip jboss-eap-8.0.0.Beta-redhat-xxxxxxxx-maven-repository.zip
$ cp -rf jboss-eap-8.0.0.Beta-maven-repository/maven-repository eap-maven-repo/
----

[NOTE]
====

To support channels, we need to inject Maven metadata so that it can fetch the latest version from the channel.
To do so, we create these metadata resources in our unzipped maven repo:

[source,bash]
----
$ cd tools
$ ./update-maven-repo.sh ~/tmp/eap-maven-repo
----

====

Once that's done, all artifacts required to build the application and provision EAP are in the `~/tmp/eap-maven-repo directory`.
Let's create a Docker image that contains this directory.

[source,bash]
----
$ cd ~/tmp
$ cat Dockerfile
FROM scratch
COPY eap-maven-repo /maven-repository
$ docker build -t eap-maven-repo .
----

### Push this image to OpenShift

[source,bash]
----
$ oc registry login
$ docker login -u openshift -p $(oc whoami -t) default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com
$ docker tag  eap-maven-repo default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com/jmesnil1-dev/eap-maven-repo
$ docker push default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com/jmesnil1-dev/eap-maven-repo
----

### Create a Helm release to build and deploy the application

[source,bash]
----
$ helm repo add wildfly http://docs.wildfly.org/wildfly-charts/
$ helm install eap-example -f helm.yaml wildfly/wildfly
----

[NOTE]
====
This example uses the `wildfly` Helm Chart and the WildFly S2I images.
They will be replaced by the `eap8` Helm Chart and teh EAP 8 S2I when they become available.
====

At the end of the S2I build phase, the application image will contain the application provisioned with EAP8.

[source,bash]
----
$ oc logs deployment/eap-offline-example
...
14:22:54,324 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: JBoss EAP 8.0.0.Beta (WildFly Core 19.0.0.Final-redhat-20220523) started in 13706ms - St
...
----



